"""Database creation

Revision ID: a4d6303da152
Revises: 
Create Date: 2024-07-03 19:36:01.139074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d6303da152'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('max_payout', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_user_id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_user_id')
    )
    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('percent_complete', sa.SmallInteger(), nullable=False),
    sa.Column('cost', sa.SmallInteger(), nullable=False),
    sa.Column('max_cost', sa.SmallInteger(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_mtm_parent',
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], )
    )
    op.create_table('activity_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_mtm_week',
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_mtm_week')
    op.drop_table('activity_day')
    op.drop_table('child_mtm_parent')
    op.drop_table('activity')
    op.drop_table('week')
    op.drop_table('parent')
    op.drop_table('child')
    # ### end Alembic commands ###
